var mode_alias_map = {
	"clike": ["C / C++ / Java"],
	"htmlmixed": ["HTML"],
	"htmlembedded": ["JSP / C#"],
	"stex": ["TeX"]
};

var mode_ext_map = {
"clike": ["c", "cpp", "h", "hpp", "c++", "java", "m", "cs", "scala"],
"clojure": ["clj"],
"coffeescript": ["coffee"],
"commonlisp": ["cl", "lisp"],
"css": ["css"],
"diff": ["diff","patch"],
"ecl": ["ecl"],
"erlang": ["erl"],
"gfm": ["md"],
"go": ["go"],
"groovy": ["groovy"],
"haskell": ["hs"],
"haxe": ["hx"],
"htmlembedded": ["jsp", "cs"],
"htmlmixed": ["html"],
"javascript": ["js", "json"],
"jinja2": [],
"less": ["less"],
"lua": ["lua"],
"markdown": ["md"],
"mysql": ["sql"],
"ntriples": ["nt"],
"ocaml": ["ocaml"],
"pascal": ["pas", "pascal"],
"perl": ["pl", "pm"],
"php":["php","phps"],
"pig": ["pig"],
"plsql":["sql"],
"properties": ["plist"],
"python":["py"],
"r": ["r"],
"rst": ["rst"],
"ruby":["rb"],
"rust": ["rust"],
"scheme": ["ss","scm"],
"shell":["sh","bash"],
"sieve": ["sieve"],
"smalltalk": ["st"],
"smarty": ["tpl"],
"sparql": ["rq"],
"stex": ["tex"],
"tiddlywiki": [],
"tiki": [],
"vb": ["vb"],
"vbscript": ["vbs"],
"velocity": ["vsl"],
"verilog": ["v", "vh"],
"xml": ["xml", "xslt"],
"xquery": ["xquery"],
"yaml": ["yaml"],
"z80": ["z80"]
};
